services:
  service1:
    build:
      context: ../
      dockerfile: service1/Dockerfile.dev
    ports:
      - "8001:8001"
    volumes:
      - ../service1:/src/service1
      - service1lib:/usr/local/lib # caching Python packages

volumes:
  service1lib: {}
